
name: "docker-push"

on:
  push:
    tags:
      - '*'  # Only runs on any tag push
    paths-ignore:
      - '**/*.md'
      - '.github/**'


jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout source code"
      uses: actions/checkout@v3

    - name: "Extract tag name"
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v1

    - name: "Log in to Docker Hub"
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: "Build and push Docker image"
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/linux-status-screen:${{ env.TAG }}
          ${{ secrets.DOCKER_USERNAME }}/linux-status-screen:latest